// https://projecteuler.net/problem=2
// Even Fibonacci numbers
// Problem 2
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

console.log("problem2");

// build fibonacci
var s = 2,
    i = 2,
    f = 0,
    arr = [1,2],
    x = true;
while (f < 4000000) {
    f = arr[i-1] + arr[i-2];
    arr.push(f);
    if (f % 2 === 0) {
        s += f;
        console.log(f, "even fib", s);
    }
    // console.log(f, s, arr);
    i++;
}
console.log(s);
console.log(arr.length);

// build fibonacci
// var f = 0,
//     arr = [1,2];
// while (f < 4000000) {
//     f = arr[]
// }