// https://projecteuler.net/problem=2
// Even Fibonacci numbers
// Problem 2
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

// My original solution from my first pass years ago. Iteration, brute force. Knock knock, Fib!
// Originally I used an array, probably now I would only keep track of the last 2 values as separate int variables to save space and array processing.
function bruteForce() {
  var s = 2,
    i = 2,
    f = 0,
    arr = [1,2],
    x = true;
  while (f < 4000000) {
    f = arr[i-1] + arr[i-2];
    arr.push(f);
    if (f % 2 === 0) {
      s += f;
    }
    i++;
  }
  return s;
}

// Ok so apparently every 3rd fibonacci number is even because the preceding 2 are odd and 2 odds added together are even 🤯🤯
// This solution is based on this information and Project Euler's second solution. Still iterating.
// 🥈 Second place
function onlyEvenFans() {
  const limit = 4000000;
  let sum = 0,
    a = 1
    b = 1
    c = a + b;
  while (c < limit) {
    sum = sum + c;
    a = b + c;
    b = c + a;
    c = a + b;
  }
  return sum;
}

// Tests
console.log(onlyEvenFans());

// What I learned
// Every 3rd fibonacci number is even because the preceding 2 numbers are odd and 2 odds added together are even. I mean it has to be this way.
// 1. odd + even = odd, 2. even + odd = odd, 3. odd + odd = even. 🤯 How did I never notice that?
// 

// Notes
